
a.out:
	# https://stackoverflow.com/questions/14228856/how-to-compile-c-with-c11-support-in-mac-terminal
	clang++ -std=c++11 -stdlib=libc++ -framework GLUT -framework OpenGL main.cpp

clean:
	rm -rf a.out
